### ISSUE TITLE
Extracting descriptors

### ISSUE THREAD

**Issue by zugexiaodui** [CVIR/ConvPrompt#3]
Hi! Thank you for your code! Is there any script of extracting descriptors for a dataset? I'm going to experiment on a new dataset but I have no idea on extracting good descriptors.

**Comment by ranarag** [comment]
Hi, 
we had used `generate_descriptors.py` of  [Visual Classification via Description from Large Language Models](https://github.com/sachit-menon/classify_by_description_release) to generate the descriptors.
